export type ProductInfoType = {
	id: string;
	namespaceId: string;
	name: string;
	capacityAvailable: string;
	capacity: string;
	priceRegular: number;
	priceDiscount: number;
	colorsAvailable: string;
	color: string;
	images: string;
	description: string;
	screen: string;
	resolution: string;
	processor: string;
	ram: string;
	camera: string;
	zoom: string;
	cell: string;
	category?: string;
	createdAt?: string;
	updatedAt?: string;
};
